# Generated by Django 3.0.7 on 2021-04-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('latitude', models.DecimalField(decimal_places=15, help_text='Latitude of sighting point', max_digits=40)),
                ('longitude', models.DecimalField(decimal_places=10, help_text='Longitude of sighting point', max_digits=40)),
                ('unique_squirrel_id', models.CharField(help_text='Unique Squirrel ID Number', max_length=40, primary_key=True, serialize=False)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='Unknown', help_text='Shift of the day', max_length=2)),
            ],
        ),
    ]
