# Generated by Django 3.0.7 on 2021-04-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Value is either Adult or Juvenile', max_length=20),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='approaches',
            field=models.BooleanField(default=False, help_text='True if the squrriel was seen approaching human'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='chasing',
            field=models.BooleanField(default=False, help_text='True if squirrel was seen chasing'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='climbing',
            field=models.BooleanField(default=False, help_text='True if squrriel was seen climbing'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='date',
            field=models.DateField(blank=True, help_text='Date of sighting', null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='eating',
            field=models.BooleanField(default=False, help_text='True if squrriel was seen eating'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='foraging',
            field=models.BooleanField(default=False, help_text='True if squrriel was seen foraging'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='indifferent',
            field=models.BooleanField(default=False, help_text='True if squirrel was indifferent to huamn presence'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='kuks',
            field=models.BooleanField(default=False, help_text='True if the squrriel was heard kuking'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='location',
            field=models.CharField(blank=True, choices=[('Ground plane', 'Ground plane'), ('Above ground', 'Above ground')], help_text='Location of squirrel', max_length=20),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='moans',
            field=models.BooleanField(default=False, help_text='True if the squrriel was heard moaning'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(blank=True, help_text='Other activities', max_length=150),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon')], default='Unknown', help_text='Value is either gray, cinnamon or black', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='quaas',
            field=models.BooleanField(default=False, help_text='True if the squrriel  was heard Quaaing'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='running',
            field=models.BooleanField(default=False, help_text='True if squirrel was seen running'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='runs_from',
            field=models.BooleanField(default=False, help_text='True if squirrel was seen running from humans'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, help_text='Specific location of squirrel', max_length=150),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_flags',
            field=models.BooleanField(default=False, help_text='True if the squrriel was seen flagging its tail'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_twitching',
            field=models.BooleanField(default=False, help_text='True if the squrriel was seen twitching its tail'),
        ),
    ]
